name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no k6zma@194.146.242.41 << 'ENDSSH'
        cd /home/k6zma/projects/DiscreteSolver
        git pull
        docker-compose down
        docker-compose up --build -d
        ENDSSH
