name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to Server
      run: |
        scp deploy.sh k6zma@194.146.242.41:/projects/DiscreteSolver/
        ssh k6zma@194.146.242.41 'bash /projects/DiscreteSolver/'
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
