name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create SSH directory
      run: mkdir -p $HOME/.ssh

    - name: Add SSH key to known hosts
      run: |
        echo "$SERVER_SSH_KEY" >> $HOME/.ssh/known_hosts
      env:
        SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}

    - name: Set permissions on SSH directory and files
      run: |
        chmod 700 $HOME/.ssh
        chmod 600 $HOME/.ssh/known_hosts

    - name: Deploy to Server
      run: |
        scp -v deploy.sh k6zma@194.146.242.41:/home/k6zma/projects/DiscreteSolver/
        ssh k6zma@194.146.242.41 'bash /home/k6zma/projects/DiscreteSolver/deploy.sh'
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
